
name: Deploy

on:
  push: # any time there is direct merging happening with the Main Branch that is when we want these jobs to execute 
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t sagarh1987/next-js-app
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push sagarh1987/next-js-app:latest


 